spring.application.name=blog-letterario

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=postgres
spring.datasource.password=root #DB TEST PER RENDERE SICURA LA PASSWORD AGGIUNGERE VARIABILE D'AMBIENTE IN ENVINRONMENT
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurazione Spring AI 
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b