spring.application.name=blog-letterario

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API KEY
spring.ai.google.genai.api-key=AIzaSyDL--I1S_TD7PSYZYY1suGc5YBwD3AE7vk
spring.ai.google.genai.chat.options.model=gemini-1.5-flash