spring.application.name=blog-letterario
#DB TEST PER RENDERE SICURA LA PASSWORD AGGIUNGERE VARIABILE D'AMBIENTE IN ENVINRONMENT
spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#FLYWAY
spring.flyway.enabled=true
#FLYWAY(SE IL DB ESISTE GIA)
spring.flyway.baseline-on-migrate=true
#FLYWAY LOCATION PATH
spring.flyway.locations=classpath:db/migration

# Configurazione Spring AI 
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b